name: CI/CD
on:
  push:
    branches:
      main
  pull_request:
    branches: ['main', 'develop']

jobs:
    TestingCodeSyntax:
        runs-on: ubuntu-latest
        steps:
        - name: Clone code repository
          uses: actions/checkout@v2
        - name: Installing Node
          uses: actions/setup-node@v2
          with:
              node-version: "16"
        - name: Installing dependencies
          run:  npm install

        - name: Run EsLint
          run: npm run lint

    TestApplicationFunctionality:
      runs-on: ubuntu-latest
      needs: TestingCodeSyntax
      if: always()
      steps:
        - name: Clone code repository
          uses: actions/checkout@v2
        - name: Installing Node
          uses: actions/setup-node@v2
          with:
            node-version: "16"

        - name: Installing dependencies
          run: npm install

        - name: Start Local Dev Server on Unit Tests
          run: nohup npm start &
          
        - name: Wait for the server to start
          run: npx wait-on http://localhost:3000

        - name: Run Cypress Tests
          run:  npm run test


    DeployChanges:
      runs-on: ubuntu-latest
      needs: TestApplicationFunctionality
      if: github.ref == 'refs/heads/main'

      steps:
        - name: Clone code repository
          uses: actions/checkout@v2
        - name: Installing Node
          uses: actions/setup-node@v2
          with:
            node-version: "16"

        - name: Installing dependencies
          run: npm install

        - name: Build Project
          run:  npm run generate

        - name: Install Vercel CLI
          run: npm install -g vercel

        - name: Deploy to Vercel
          run:  vercel --token ${{ secrets.VERCEL_DEPLOY_TOKEN }} --prod